/*
  # Create License Key System

  1. New Tables
    - `license_keys`
      - `id` (uuid, primary key)
      - `key` (text, unique) - The license key string (format: XXXX-XXXX-XXXX-XXXX)
      - `duration_days` (integer) - Number of days the key is valid after activation
      - `status` (text) - One of: 'active', 'inactive', 'expired', 'revoked'
      - `created_by` (text) - Admin who created the key
      - `activated_by` (uuid, nullable) - User who activated the key
      - `activated_at` (timestamptz, nullable) - When the key was activated
      - `expires_at` (timestamptz, nullable) - When the key expires
      - `created_at` (timestamptz) - When the key was created
      - `notes` (text, nullable) - Admin notes about the key
    - `license_activations`
      - `id` (uuid, primary key)
      - `license_key_id` (uuid, foreign key to license_keys)
      - `user_id` (uuid) - The user who activated
      - `device_fingerprint` (text, nullable) - Browser fingerprint for device tracking
      - `activated_at` (timestamptz)
      - `expires_at` (timestamptz)
      - `is_active` (boolean)

  2. Security
    - Enable RLS on both tables
    - Admin can do everything (service role)
    - Users can only read their own activations
    - Public can validate keys (INSERT only on license_activations for activation)

  3. Important Notes
    - Keys are generated by admins with a specified duration
    - A key starts as 'inactive' and becomes 'active' when a user activates it
    - The expires_at is calculated as activated_at + duration_days
    - A cron or check will mark keys as 'expired' when expires_at passes
*/

CREATE TABLE IF NOT EXISTS license_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  duration_days integer NOT NULL DEFAULT 30,
  status text NOT NULL DEFAULT 'inactive' CHECK (status IN ('inactive', 'active', 'expired', 'revoked')),
  created_by text NOT NULL DEFAULT 'admin',
  activated_by uuid,
  activated_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now(),
  notes text DEFAULT ''
);

ALTER TABLE license_keys ENABLE ROW LEVEL SECURITY;

-- Admin (service role) has full access
CREATE POLICY "Service role can do everything on license_keys"
  ON license_keys
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Users can read keys they activated
CREATE POLICY "Users can read own activated keys"
  ON license_keys
  FOR SELECT
  TO authenticated
  USING (activated_by = auth.uid());

-- Public can read key status for validation (by key value)
CREATE POLICY "Public can validate keys by key value"
  ON license_keys
  FOR SELECT
  TO anon
  USING (true);


CREATE TABLE IF NOT EXISTS license_activations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  license_key_id uuid NOT NULL REFERENCES license_keys(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  device_fingerprint text DEFAULT '',
  activated_at timestamptz DEFAULT now(),
  expires_at timestamptz NOT NULL,
  is_active boolean DEFAULT true
);

ALTER TABLE license_activations ENABLE ROW LEVEL SECURITY;

-- Service role full access
CREATE POLICY "Service role can do everything on license_activations"
  ON license_activations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Users can read their own activations
CREATE POLICY "Users can read own activations"
  ON license_activations
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- Users can insert activations (for key activation)
CREATE POLICY "Users can insert own activations"
  ON license_activations
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());


-- Index for fast key lookups
CREATE INDEX IF NOT EXISTS idx_license_keys_key ON license_keys(key);
CREATE INDEX IF NOT EXISTS idx_license_keys_status ON license_keys(status);
CREATE INDEX IF NOT EXISTS idx_license_activations_user ON license_activations(user_id);
CREATE INDEX IF NOT EXISTS idx_license_activations_expires ON license_activations(expires_at);
